import { initRollbar } from "./helpers/rollbar";
import "core-js/stable";
import "regenerator-runtime/runtime";
import "js/publicpath";
import "bootstrap";
import "styles/global.scss";
import "./react/scenes/index";
import "webp-images/CMSCreativeKingfisher.jpg?sizes[]=100&sizes[]=200";
import "images/CMSCreativeKingfisher2.jpg";
initRollbar();
